config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  authenticated :user do
    root to: 'pages#login_home'
  end
  unauthenticated :user do
    root to: 'pages#home', as: :unauthenticated_root
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :users, only: [:show]
  resources :projects do
    get "success", on: :member
  end
  resources :polls do
    get "success", on: :member
    get "responds", on: :member
    resources :answers, only: [:new, :create, :destroy]
  end
  resources :answers, only: [] do
    resources :votes, only: [:create]
  end
  resources :guests, only: :create
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :poll
  has_many :votes, dependent: :destroy

  validates :title, presence: true
  validates :poll, presence: true

  def votes_count
    votes.count
  end

  def votes_percentage
    # return 0 if poll.votes_count == 0

    votes_count / poll.votes_count.to_f * 100
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/poll.rb
class Poll < ApplicationRecord
  belongs_to :user
  belongs_to :project, optional: true
  has_many :answers, dependent: :destroy
  has_many :votes, through: :answers
  accepts_nested_attributes_for :answers, reject_if: :all_blank, allow_destroy: true

  validates :title, presence: true
  validates :user, presence: true
  validates :deadline, presence: true

  def votes_count
    votes.count
  end

  def user_voted?(user_or_name)
    if user_or_name.class == User
      !votes.where(user: user_or_name).empty?
    elsif user_or_name.class == String
      !votes.where(name: user_or_name).empty?
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :polls, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Also available: user_signed_in? and current_user

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :polls, dependent: :destroy
  has_many :projects, dependent: :destroy
  has_one_attached :avatar

  def initials
    "#{name.first}"
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :answer
  belongs_to :user, optional: true

  validate :one_vote_per_poll, :deadline_valid

  def one_vote_per_poll
    if user_id != nil
      unless answer.poll.votes.where(user_id: self.user_id).empty?
        errors.add(:one_vote_per_poll, ":)")
      end
    else
      unless answer.poll.votes.where(name: self.name).empty?
        errors.add(:one_vote_per_poll, ":)")
      end
    end
  end

  def deadline_valid
    if (answer.poll.deadline.to_datetime - DateTime.current).negative?
      errors.add(:poll_has_ended, ":(")
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy
    poll = @answer.poll
    if poll.project_id.nil?
      redirect_to polls_path
    else
      redirect_to project_path(poll.project_id)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation, :current_password, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password, :password_confirmation, :current_password, :avatar])
  end

  def afer_sign_out_path_for(resource)
    unauthenticated_root_path
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  skip_before_action :authenticate_user!, only: :create

  def create
    session[:name] = params[:guest][:name]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def login_home
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  skip_before_action :authenticate_user!, only: :show

  def index
    if params[:query].present?
      @polls = current_user.polls.where("title ILIKE ?", "%#{params[:query]}%")
    else
      @polls = current_user.polls
    end

    @polls = @polls.order(deadline: :asc)

    @open_polls = @polls.where("deadline >= ?", DateTime.now)
    @closed_polls = @polls.where("deadline < ?", DateTime.now)
  end

  def show
    # @poll = current_user.polls.find(params[:id])
    @poll = Poll.find(params[:id])
  end

  def new
    @poll = Poll.new
  end

  def create
    @poll = Poll.new(poll_params)
    @poll.user = current_user
    if @poll.save
      redirect_to success_poll_path(@poll)
    else
      render :new
    end
  end

  def edit
    @poll = current_user.polls.find(params[:id])
  end

  def update
    @poll = Poll.find(params[:id])
    @poll.update(poll_params)
    if @poll.project_id.nil?
      redirect_to polls_path
    else
      redirect_to project_path(@poll.project_id)
    end
  end

  def destroy
    @poll = Poll.find(params[:id])
    @poll.destroy
    if @poll.project_id.nil?
      redirect_to polls_path
    else
      redirect_to project_path(@poll.project_id)
    end
  end

  def update_answer
    if poll.update_answer(poll_params_answer)
      redirect_to polls_path
    else
      render :edit
    end
  end

  def success
    @poll = Poll.find(params[:id])
  end

  def responds
    @poll = Poll.find(params[:id])
  end

  private

  def poll_params
    params.require(:poll).permit(:title, :description, :deadline, :project_id, answers_attributes: [:id, :title, :poll, :_destroy])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :authenticate_user!, only: :show

  def new
    # only the ones without project
    @polls = Poll.where(project_id: nil)
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    if @project.save
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def show
    @project = Project.find(params[:id])
    @project.polls
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    @project.update(project_params)
    redirect_to project_path(@project)
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to root_path
  end

  def success
    @project = Project.find(params[:id])
  end

  private

  def project_params
    params.require(:project).permit(:title, :description)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  skip_before_action :authenticate_user!, only: :create

  def create
    @vote = Vote.new
    @vote.answer = Answer.find(params[:answer_id])
    if user_signed_in?
      @vote.user = current_user
    else
      @vote.name = session[:name]
    end
    flash[:alert] = @vote.errors.full_messages.join(", ") unless @vote.save
    if user_signed_in?
      if @vote.answer.poll.project_id.nil?
        redirect_to polls_path
      else
        redirect_to project_path(@vote.answer.poll.project_id)
      end
    else
      redirect_to poll_path(@vote.answer.poll)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_bg_color(string)
    percentage = string.sum % 360

    "hsl(#{percentage}, 100%, 50%)"
  end
end

app/views/answers/new.html.erb
<h1>Create answer</h1>
<%= simple_form_for(@answer) do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :deadline %>
  <%= f.association :project %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DealApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel=“stylesheet” href=“https://use.fontawesome.com/releases/v6.1.1/css/all.css”>

    <%= favicon_link_tag asset_path ('logo.png') %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'pages/partials/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="landing">
  <img class="imagen-landing" src="https://images.unsplash.com/photo-1551730459-92db2a308d6a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80">
  <div class="margin">
    <p class="homep" style="font-size: 25px"><strong>Welcome to 👋🏻</strong></p>
    <div style="height: 65px">
      <h1 class="font-size:25px" data-controller="typed-js"></h1>
    </div>
    <p class="homep" style="font-size: 25px"><strong>The best app to make superfast decisions</strong></p>
  </div>
  <div class="buttons-landing">
    <%= link_to "Create a Poll", new_poll_path, class:"btn btn-main", style: "font-size:24px; width:85%" %>
    <%= link_to "Login", new_user_session_path, class:"link pt-3" %>
  </div>
</div>

app/views/pages/login_home.html.erb
<div class="title-link">
  <h1 class="titlepoll">HELLO!</h1>

  <%# Edit button coming soon: First need profile page %>
  <%= link_to "Edit", edit_user_registration_path %>
</div>

<div class="profileblock">

  <%# Total polls created %>
  <div class="polls">
    <% polls_count = 0 %>
    <%# <% current_user.projects.each do |project| %>
      <%# <% polls_count += project.polls.count %>
    <%# <% end %>
    <% polls_count += current_user.polls.count %>

    <p style="font-size: 35px; color:white"><%= polls_count %></p>
    <p style="font-size: 13px; color:white">polls</p>
  </div>

  <div>
    <% if current_user.avatar.attached? %>
      <%= image_tag(current_user.avatar, width: "80px", style: "width: 80px; border-radius: 50%", class: "avatar-profile" )%>
    <% else %>
      <%= image_tag "avatar.png", style: "width: 80px; border-radius: 50%", class: "avatar-profile" %>
    <% end %>


      <%# Total votes created %>
    <div class="votes">
      <% vote_count = 0 %>
      <%# <% current_user.projects.each do |project| %>
        <%# <% project.polls.each do |poll| %>
          <%# <% vote_count += poll.votes.count %>
        <%# <% end %>
      <%# <% end %>
      <% current_user.polls.each do |poll| %>
        <% vote_count += poll.votes.count %>
      <% end %>
      <div>
        <p style="font-size: 35px; color:white"><%= vote_count %></p>
        <p style="font-size: 13px; color:white">votes</p>
      </div>
    </div>
  </div>

  <%# Total projects created %>
  <div class="projects">
    <p style="font-size: 35px; color:white"><%= current_user.projects.count %></p>
    <p style="font-size: 13px; color:white">projects</p>
  </div>

</div>

<%# POLLS %>
<div class="title-link">
  <h2 class="titlepoll" style="font-size: 25px">Last poll</h2>
  <%= link_to 'See all', polls_path %>
</div>

<ul>
  <% current_user.polls.last(1).each do |poll| %>
    <div class="container-poll">
      <li>
        <%= render "polls/poll", poll: poll %>
      </li>
    </div>
  <% end %>
</ul>

<div class="container-button" style="padding-bottom: 0">
  <span class="btn-main">
    <%= link_to "Create new poll", new_poll_path %>
  </span>
</div>


<%# PROJECTS %>
<h2 class="titlepoll" style="font-size: 25px">All my projects</h2>
<ul>
  <% current_user.projects.each do |project| %>
  <div class="container-projects" style="margin: 0% 5% 2% 5%">
      <li class="project-names">
          <div>
          <%= link_to project_path(project) do %>
            <p style="color: #000A63"><strong><%= project.title.upcase_first %></strong></p>
          </div>
          <div>
              <% if project.polls.count == 1 %>
                <p><%= project.polls.count %> poll</p>
              <% else %>
                <p><%= project.polls.count %> polls</p>
              <% end %>
          </div>
          <% end %>
      </li>
    </div>
  <% end %>
</ul>

<div class="container-button">
  <span class="btn-main">
    <%= link_to "Create new project", new_project_path %>
  </span>
</div>

app/views/pages/partials/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-bottom">
  <div class="container-fluid">
      <ul class="navbar-nav me-auto navpoll">
        <% if user_signed_in? %>
          <li class="nav-item liclasshome">
            <%= link_to root_path, class: "nav-link" do %>
            <i class="fas fa-home iconsnavbarhome"></i>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to polls_path, class: "nav-link" do %>
            <i class="fas fa-question iconsnavbar"></i>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_poll_path, class: "nav-link" do %>
            <i class="fas fa-plus-circle iconsnavbarplus"></i>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to "#", class: "nav-link", data: {bs_toggle:"modal", bs_target:"#searchModal"} do %>
              <i class="fas fa-search iconsnavbar"></i>
            <% end %>
          </li>
          <li class="nav-item dropdown">
            <% if current_user.avatar.attached? %>
              <%= link_to edit_user_registration_path do %>
                <%= image_tag current_user.avatar, class: "avatar dropdown-toggle" %>
              <% end %>
            <% end %>
          </li>
        <% end %>
      </ul>
  </div>
</div>

</button>

<!-- Modal -->
<div class="modal fade" id="searchModal" tabindex="-1" aria-labelledby="searchModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-fullscreen">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="searchModalLabel"></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <!-- Search form -->
        <h1 class="titlepoll titlesearch"> SEARCH</h1>
        <%= form_tag polls_path, method: :get do %>
          <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Find a poll"
          %>
          <%= submit_tag "Search", class: "search-button" %>
          <img src="https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?ixlib=rb-1.2.1&ixid=MnwxM[…]G90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=717&q=80" class="searchimage">
        <% end %>
        <!-- End of search form -->
      </div>
    </div>
  </div>
</div>

app/views/polls/_answer_form.html.erb
<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>">
  <%# <%= f.label :title, :label => "Option" %>
  <div class="poll-answer-votes">
    <%= f.text_field :title, placeholder: "Write an option" %>
    <button type="button" data-action="nested-form#remove"><i class="fas fa-trash answertrash"></i></button>
  </div>
  <%= f.hidden_field :_destroy %>
</div>

app/views/polls/_poll.html.erb
<div>
  <div class="container-poll-title">
    <h3><%= poll.title.upcase_first %></h3>
  </div>

  <p><%= poll.description.upcase_first %></p>

  <%# ONLY DISPLAY PROJECT NAME IF IT EXISTS %>

  <div>
    <ul>
      <% if poll.user_voted?(current_user || session[:name]) || poll.user_id == current_user&.id %>
        <% poll.answers.each do |answer| %>
          <li class="poll-answer-votes position-relative">
            <span class="vote-percentage-bar" style="width: <%= answer.votes_percentage %>%;"></span>
            <%= link_to answer_votes_path(answer.id), remote: true, method: :post, 'data-turbolinks-scroll': false do %>
              <div class="answer-vote-percentage">
                <p><%= answer.title.upcase_first %> (<%= pluralize(answer.votes_count, "vote") %>)</p>
                <p><%= answer.votes_percentage.nan? ? "0" : answer.votes_percentage.to_i %> %</p>
              </div>
            <% end %>
          </li>
        <% end %>
      <% else %>
        <% poll.answers.each do |answer| %>
          <li class="poll-answer-votes position-relative">
            <%= link_to answer_votes_path(answer.id), remote: true, method: :post, 'data-turbolinks-scroll': false do %>
              <div class="answer-vote-percentage">
                <p><%= answer.title.upcase_first %></p>
              </div>
            <% end %>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>

  <div class="deadline-and-icons">
    <%# HAS ENDED %>
    <% if (poll.deadline.to_datetime - DateTime.now).negative? %>
      <p>🕒 This poll has ended</p>
    <%# ENDS WITHIN 24 H %>
    <% elsif ((poll.deadline.to_datetime - DateTime.now.to_datetime) * 24) < 26 %>
    <%# MORE THAN ONE HOUR %>
      <% if (((poll.deadline.to_datetime - DateTime.now) * 24).to_i - 1) > 1 %>
        <p>🕒 <%= ((poll.deadline.to_datetime - DateTime.now) * 24).to_i - 2 %>h <%= ( (((poll.deadline.to_datetime - DateTime.now) * 1440).to_i - 120) - ((((poll.deadline.to_datetime - DateTime.now) * 24).to_i - 2) * 60)) %>m left</p>
      <%# LESS THAN ONE HOUR %>
      <% else %>
        <p>🕒 <%= ((poll.deadline.to_datetime - DateTime.now) * 1440).to_i - 120 %>m left</p>
      <% end %>
    <%# TOMORROW %>
    <% elsif (poll.deadline.day) == (DateTime.now.day + 1) %>
      <p>🕒 1d
      <%= ( (((poll.deadline.to_datetime - DateTime.now) * 24).to_i - 2) - ((poll.deadline.to_datetime - DateTime.now).to_i * 24) )%>h
      <%= ( ((((poll.deadline.to_datetime - DateTime.now) * 1440).to_i)) - ((((poll.deadline.to_datetime - DateTime.now) * 24).to_i - 2) * 60) - 120)%>m left</p>
    <%# FUTURE %>
    <% else %>
      <p>🕒 <%= (poll.deadline.to_datetime - DateTime.now).to_i %>d
      <%= ( (((poll.deadline.to_datetime - DateTime.now) * 24).to_i - 2) - ((poll.deadline.to_datetime - DateTime.now).to_i * 24) )%>h
      <%= ( ((((poll.deadline.to_datetime - DateTime.now) * 1440).to_i)) - ((((poll.deadline.to_datetime - DateTime.now) * 24).to_i - 2) * 60) - 120)%>m left</p>
    <% end %>

    <% if poll.user == current_user %>
      <div>
        <%= link_to responds_poll_path(poll) do %>
          <i class="fas fa-eye fasicont"></i>
        <% end %>
        <%= link_to success_poll_path(poll) do %>
          <i class="fas fa-share-alt fasicont"></i>
        <% end %>
        <%= link_to poll_path(poll), method: :delete, data: { confirm: "Are you sure you want to detete this poll?" } do %>
          <i class="fas fa-trash fasicont"></i>
        <% end %>
        <%= link_to edit_poll_path(poll) do %>
          <i class="fas fa-pencil-alt fasicont"></i>
        <% end %>
      </div>
    <% end %>

  </div>

    <% unless poll.project.nil? %>
    <p class="label-project"><%= poll.project.title.upcase_first %></p>
  <% end %>
</div>

app/views/polls/edit.html.erb
<h1 class="titlepoll">EDIT POLL</h1>
<%= render partial: "form", locals: {poll: @poll} %>

app/views/polls/index.html.erb
<div style="margin: 30px 30px 0px 30px;">
  <%= link_to root_path, class: "back" do %>
  <i class="fas fa-undo iconsnavbar"></i>
  <% end %>
</div>

<div class="title-with-avatar">
  <h1 class="titlepoll" style="margin-top: 5%">ALL POLLS</h1>
  <%# user-avatar goes here %>
    <% if current_user.avatar.attached? %>
      <%= image_tag current_user.avatar, style: "width: 70px; border-radius: 50%; margin-right: 20px; height: 57px; object-fit: cover", class: "avatar-profilepoll" %>
    <% else %>
      <%= image_tag "avatar.png", style: "width: 70px; border-radius: 50%; margin-right: 20px; height: 57px; object-fit: cover", class: "avatar-profilepoll" %>
    <% end %>
    </div>


<p style="font-size: 20px; margin-left: 5%; margin-bottom: 5%;"> <strong> ✅ Active polls </strong></p>
<ul>
  <% @open_polls.each do |poll| %>
    <div class="container-poll" id="<%= poll.id %>">
      <li>
        <%= render "polls/poll", poll: poll %>
      </li>
    </div>
  <% end %>
</ul>

<p style="font-size: 20px; margin-left: 5%; margin-bottom: 5%;"> <strong> ❌ Inactive polls </strong></p>
<ul>
  <% @closed_polls.each do |poll| %>
    <div class="container-poll">
      <li>
        <%= render "polls/poll", poll: poll %>
      </li>
    </div>
  <% end %>
</ul>

<div class="container-button">
  <span class="btn-main">
    <%= link_to "Create poll", new_poll_path %>
  </span>
</div>

app/views/polls/new.html.erb
<h1 class="titlepoll">CREATE A POLL</h1>
<%= render partial: "form", locals: {poll: @poll} %>

app/views/polls/responds.html.erb
<%# Back button %>
<div style="margin: 30px 30px 0px 30px;">
  <% if @poll.project.nil? %>
    <% back = polls_path(anchor: @poll.id) %>
  <% else %>
    <% back = project_path(@poll.project) %>
  <% end %>
  
  <%= link_to back, class: "back" do %>
    <i class="fas fa-undo iconsnavbar"></i>
  <% end %>
</div>

<h1 class="titlepoll">RESPONSES</h1>
<h2 class="titlepoll" style="font-size: 25px"><%= @poll.title %></h2>

<div class="project-description-options">
  <p><%= @poll.description %></p>
</div>

<div class="responses-container">
  <ul style="padding-bottom: 180px">
    <% @poll.answers.each do |answer| %>
      <li class="poll-answer-votes position-relative">
        <span class="vote-percentage-bar" style="width: <%= answer.votes_percentage %>%;"></span>
        <%= link_to answer_votes_path(answer.id), remote: true, method: :post, 'data-turbolinks-scroll': false do %>
          <div class="answer-vote-percentage">
            <p><%= answer.title.upcase_first %> (<%= pluralize(answer.votes_count, "vote") %>)</p>
            <p><%= answer.votes_percentage.nan? ? "0" : answer.votes_percentage.to_i %> %</p>
          </div>
        <% end %>
      </li>


      <p style="font-weight:bold; font-size: 17px">Respondents ▾</p>

      <ul>
        <% if answer.votes.empty? %>
          <li>
            <div class="respondent-info">
              <p>No votes for this answer</p>
            </div>
          </li>
        <% end %>
        <% answer.votes.each do |vote| %>
          <li>
            <div class="respondent-info">
              <% if vote.user_id %>
                <div class="initial-background" style="background-color: <%= avatar_bg_color(vote.user.name) %>">
                  <span class="initial"><%= vote.user.initials.upcase_first %></span>
                </div>
                <p><%= vote.user.name.upcase_first %></p>
              <% else %>
                <div class="initial-background" style="background-color: <%= avatar_bg_color(vote.name) %>">
                  <span class="initial"><%= vote.name.first.upcase_first %></span>
                </div>
                <p><%= vote.name.upcase_first %></p>
              <% end %>
            </div>
          </li>
        <% end %>
      </ul>
    <% end %>
  </ul>
</div>


<script>
  // const setBackgroundColor = () => {
  //   const avatars = document.querySelectorAll('.initial-background')
  //   avatars.forEach(element => {
  //       function random_bg_color() {
  //         var x = Math.floor(Math.random() * 256);
  //         var y = Math.floor(Math.random() * 256);
  //         var z = Math.floor(Math.random() * 256);
  //         var bgColor = "rgb(" + x + "," + y + "," + z + ")";
  //         console.log(bgColor);
  //         element.style.backgroundColor = bgColor
  //       }
  //       random_bg_color();
  //   });
  // };
  // window.onload = setBackgroundColor;
</script>

app/views/polls/show.html.erb
<h1 style="text-align: center; padding: 50px 0px 25px 0px">DEAL.</h1>

<%= image_tag @poll.user.avatar, class: "avatar-show" %>

<% unless user_signed_in? || !session[:name].nil? %>
  <!-- Modal -->
    <div id="myModal" class="modal fade" data-controller="open-modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                  <h2 class="titlepoll titlesearch" style="text-align:center" id="exampleModalLabel">Enter your name and don't forget to vote!</h2>
                </div>
                <%= simple_form_for :guest, url: guests_path, remote: true do |f| %>
                  <div class="modal-body">
                    <%= f.input :name %>
                  </div>
                  <div class="modal-footer">
                    <%= f.submit class: "btn btn-primary search-button", data: { bs_dismiss: "modal"} %>
                  </div>
                <% end %>
            </div>
        </div>
    </div>

<% end %>

<ul>
  <div class="container-poll">
    <li>
      <%= render "polls/poll", poll: @poll %>
    </li>
  </div>
</ul>

app/views/projects/edit.html.erb
<h1 class="titlepoll">EDIT PROJECT</h1>
<div class="poll-form">
<%= simple_form_for(@project) do |f| %>
  <%= f.input :title, :label => "Title", placeholder: "Write a title" %>
  <%= f.input :description, :label => "Description", placeholder: "Write a description" %>
  <%= f.submit class: "crproject" %>
<% end %>
</div>

app/views/projects/show.html.erb
<%# Back button %>
<div style="margin: 30px 30px 0px 30px;">
  <%= link_to root_path, class: "back" do %>
  <i class="fas fa-undo iconsnavbar"></i>
  <% end %>
</div>

<div class="title-with-avatar">
  <h1 class="titlepoll" style="margin-top: 5%"><%= @project.title.upcase %></h1>
  <%# user-avatar goes here %>
  <% if current_user.avatar.attached? %>
    <%= image_tag current_user.avatar, style: "width: 70px; border-radius: 50%; margin-right: 20px; height: 57px; object-fit: cover" %>
  <% else %>
    <%= image_tag "avatar.png", style: "width: 70px; border-radius: 50%; margin-right: 20px; height: 57px; object-fit: cover" %>
  <% end %>
</div>

<div style="margin: 0px 0px 0px 25px; font-size: 17px;">
  <div class="icons-show-projects">
    <%= link_to success_project_path(@project) do %>
      <i class="fas fa-share-alt fasicont"></i>
    <% end %>

    <%= link_to project_path(@project), method: :delete, data: { confirm: "Are you sure you want to delete this project?" } do %>
      <i class="fas fa-trash fasicont"></i>
    <% end %>

    <%= link_to edit_project_path do %>
      <i class="fas fa-pencil-alt fasicont"></i>
    <% end %>
  </div>
</div>

<div class="project-description-options">
  <p><%= @project.description.upcase_first %></p>
</div>

<ul>
  <% @project.polls.order(deadline: :asc).each do |poll| %>

    <div class="container-poll">
      <li>
        <%= render "polls/poll", poll: poll %>
      </li>
    </div>

  <% end %>
</ul>

<div class="container-button">
  <span class="btn-main">
    <%= link_to "Create poll", new_poll_path %>
  </span>
</div>